# -*- coding: utf-8 -*-
"""AIDI-1111-01 - Math - Assignment 2 - Algebra - Question 28 - 3b - Ravina Jivnani-100854893.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xu7fnuRioDcfTRv4lh6vHOwXHLk-elg1

**Program to multiply two matrices using nested loops**
"""

A = [[1,1/2,1/3],
    [1/2,1/3,1/4],
    [1/3,1/4,1/5]]

B = [[1.00,0.33,0.20],
    [0.33,0.20,0.15],
    [0.20,0.15,0.11]]

AxB = [[0,0,0],
         [0,0,0],
         [0,0,0]]

for x in range(len(A)):
   for y in range(len(B[0])):
       for z in range(len(B)):
           AxB[x][y] += A[x][z] * B[z][y]
for r in AxB:
   print(r)